# Generated by Django 5.2 on 2025-04-26 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("loction", models.CharField(max_length=250)),
                ("organizer", models.CharField(max_length=250)),
                (
                    "status",
                    models.CharField(
                        choices=[("ON", "Online"), ("OF", "Offline")],
                        default="OF",
                        max_length=2,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="events_even_date_13e470_idx")
                ],
            },
        ),
    ]
