# Generated by Django 5.2 on 2025-04-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_rename_loction_event_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="author",
            new_name="user",
        ),
    ]
