# Generated by Django 5.2 on 2025-04-28 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_eventregistration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date", "created"]},
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="events_even_date_13e470_idx",
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["date", "created"], name="events_even_date_161afa_idx"
            ),
        ),
    ]
