# Generated by Django 5.2 on 2025-04-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(max_length=250, unique_for_date="date"),
        ),
    ]
