# Generated by Django 5.2 on 2025-04-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly event identifier",
                max_length=250,
                unique_for_date="date",
            ),
        ),
    ]
